events {}

http {

  # Validação do token (O Nginx já trata maiúsculas/minúsculas automaticamente aqui)
  map $http_authorization $token_valido {
    "Bearer TCC_MACKENZIE_SECRET_TOKEN_2026"  1;
    "TCC_MACKENZIE_SECRET_TOKEN_2026"         1;
    default                                  0;
  }

  # SERVER 1: Data Gateway (Dado Clínico do Prontuário)
  server {
    listen 80;
    server_name data.guarnieri.studio nginx localhost;

    location /nginx/paciente {
      # Criamos uma flag de validação híbrida
      set $acesso_permitido 0;

      # 1. Se o token mapeado acima for válido, libera
      if ($token_valido = 1) {
        set $acesso_permitido 1;
      }

      # 2. Se a requisição vier da rede interna do Docker (EDC Provedor), libera
      if ($remote_addr ~ "^172\.(1[6-9]|2[0-9]|3[0-1])\.") {
        set $acesso_permitido 1;
      }

      # Se nenhuma das condições acima for atendida, barra com 401
      if ($acesso_permitido = 0) {
        return 401 '{"error":"Unauthorized"}';
      }

      add_header Content-Type application/json;
      add_header Access-Control-Allow-Origin *;

      # Serve o arquivo independente da estrutura de barras que o EDC inventar
      rewrite ^/nginx/paciente.*$ /patient-bundle.json break;
      root /usr/share/nginx/html;
    }

    # Fallback de segurança para o arquivo local
    location = /patient-bundle.json {
      root /usr/share/nginx/html;
      default_type application/json;
    }
  }

  # SERVER 2: Proxy para o Control Plane do Provider 1
  server {
    listen 80;
    server_name provider1.guarnieri.studio;
    location / {
      proxy_pass http://edc-provider-1:19193;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }

  # SERVER 3: Proxy para o Control Plane do Provider 2
  server {
    listen 80;
    server_name provider2.guarnieri.studio;
    location / {
      proxy_pass http://edc-provider-2:19193;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }

  # SERVER 4: Proxy para o Control Plane do Consumer
  server {
    listen 80;
    server_name consumer.guarnieri.studio;
    location / {
      proxy_pass http://edc-consumer-1:29193;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }

  # SERVER 5: Proxy para o Catálogo Federado
  server {
    listen 80;
    server_name catalog.guarnieri.studio;
    location / {
      proxy_pass http://edc-federated-catalog:49193;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }

}
